name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_build_and_test:
    name: Build and test (Linux)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: ['1.19', '1.20', '1.21']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
    - id: go
      name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: go build -v .
    - name: Test
      run: go test -v .
